Document: waxeye
Title: Debian waxeye Manual
Author: <insert document author here>
Abstract: This manual describes what waxeye is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/waxeye/waxeye.sgml.gz

Format: postscript
Files: /usr/share/doc/waxeye/waxeye.ps.gz

Format: text
Files: /usr/share/doc/waxeye/waxeye.text.gz

Format: HTML
Index: /usr/share/doc/waxeye/html/index.html
Files: /usr/share/doc/waxeye/html/*.html
